### ISSUE TITLE
As a customer/visitor, I want to be able to add a product to my cart so I can collect my desired products in one place

### ISSUE THREAD

**Issue by somecallmehans** [yellow-yetis/grace-shopper#4]
Frontend Tasks:

- Create a skeleton Cart react component
- Create an "Add to cart" button component that has an onClick handler function to add a product to a users cart
- Update redux store w/ action type, creator, thunk, and reducer to fetch products currently in users cart + update store when user adds new items to cart

Backend Tasks:

- Create a GET route to retrieve all of the products in a users cart
- Create a PUT route to update the users cart with the item they selected

**Comment by somecallmehans** [comment]
Potential implementation strategy: we utilize sessionStorage.setItem('key', 'value') to save any item users add to their cart regardless of signed in status (this can happen in the onClick in side of the single product view when adding to cart). Additionally in the onClick, we do a check if the user is signed in or not (w/ the auth) and if yes also make a PUT request to update cartLiquor w/ the product info user is adding to cart. This will ensure this info is saved both in sessionStorage (for if users are not signed in/guest) as well as in the cartLiquor db table (for signed in users to have cart persistance). 

The next step will be on the actual cart page, again using auth to see if the user is signed in or not. If yes, then we fetch the items from cartLiquor using the users cart id. If no, then we use sessionStorage.getItem('key') to load items in the cart. Then, once user completes checkout, we clear sessionStorage/update the db once more.

Open questions:
-When assigning key/value to sessionStorage, value will have to be an object that matches fields in cartLiquor to ensure parity. Key needs to be set in a way so that we can easily access these items from storage in the cart when it renders, so need to figure out what that is.

**Comment by devaratpatel** [comment]
Need to logic on line 20. (logic is automatically adding webpack login garbage).
